---
- hosts: prodServer
  become: yes
  tasks:
  - name: Install Docker
    apt:
      pkg: docker.io
      state: present
    notify:
    - apt cache update
  - name: Start Docker Service
    service:
      name: docker
      state: started
      enabled: yes
  handlers:
  - name: apt cache update
    apt:
      update_cache: yes
...
