---
- hosts: testServer
  become: yes
  tasks:
  - name: Stop Running All Containers
    command: sudo docker stop eudreka-php-app
  - name: Remove All existing Containers
    command: sudo docker rm eudreka-php-app
...
